apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: {{ .Values.managedCertificate.name | quote }}
  labels:
  {{- include "pong-crds.labels" . | nindent 4 }}
spec:
  domains:
    {{- range (sortAlpha .Values.managedCertificate.domains) }}
    - {{ . }}
    {{- end }}
