apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  annotations:
    "meta.helm.sh/release-name": "${HELM_RELEASE_NAME}"
    "meta.helm.sh/release-namespace": "${HELM_RELEASE_NAMESPACE}"
  labels:
    "app.kubernetes.io/managed-by": Helm
data:
  partial-vault.hcl: |2
    seal "gcpckms" {
      project    = "${CLOUDSDK_CORE_PROJECT}"
      region     = "${CLOUDSDK_COMPUTE_REGION}"
      key_ring   = "${VAULT_KMS_KEY_RING}"
      crypto_key = "${VAULT_KMS_AUTOUNSEAL_KEY}"
    }

    storage "gcs" {
      bucket     = "${VAULT_GCS_BUCKET}"
      ha_enabled = "true"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-cd
  annotations:
    "meta.helm.sh/release-name": "${HELM_RELEASE_NAME}"
    "meta.helm.sh/release-namespace": "${HELM_RELEASE_NAMESPACE}"
  labels:
    "app.kubernetes.io/managed-by": Helm
type: Opaque
data:
  service_account_key.json: "${VAULT_SA_KEY_BASE64}"
