#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

HELM_VERSION=3.4.1
HELMFILE_VERSION=0.135.0

CLOUDBUILD_CONFIG_PATH="$1"

sed -E \
  "s/HELM_VERSION=.+/HELM_VERSION=v${HELM_VERSION}\",/" \
  -i "${CLOUDBUILD_CONFIG_PATH}"

sed -E \
  "s/HELMFILE_VERSION=.+/HELMFILE_VERSION=v${HELMFILE_VERSION}\",/" \
  -i "${CLOUDBUILD_CONFIG_PATH}"

cat "${CLOUDBUILD_CONFIG_PATH}"
